%% do forward kinematics of 7 link arm
function pos = fkTrial(joints,linkLengths,target)
    global h_axes link1 link2 link3 link4 link5 link6 link7 targetVisual;

    %initialize T
    T = eye(4);
    
    %get all homogeneous transformation matrices
    for i=1:length(linkLengths)*3
        B = eye(4);
        if mod(i,3) == 1
            %homogeneous transformation matrix for roll (Rx)
            A(:,:,i) = [1        0                  0          0; ...
                        0   cos(joints(i))   -sin(joints(i))   0; ...
                        0   sin(joints(i))    cos(joints(i))   0; ...
                        0        0                  0          1];
        elseif mod(i,3) == 2
            %for pitch (Ry)
            A(:,:,i) = [cos(joints(i))   0    sin(joints(i))   0; ...
                        0                1         0           0; ...
                        -sin(joints(i))  0    cos(joints(i))   0; ...
                        0                0         0           1];
        elseif mod(i,3) == 0
            %for yaw (Rz)  
            A(:,:,i) = [cos(joints(i))   -sin(joints(i))   0    0; ...
                        sin(joints(i))    cos(joints(i))   0    0; ...
                        0                      0           1    0; ...
                        0                      0           0    1];
            B(1,4) = linkLengths(i/3);
        end
        T = T * A(:,:,i) * B;
        if mod(i,3) == 0
            positions(:,i/3) = T(1:3,4);
        end
    end
    
    %draw all links
    set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                               'Ydata',[0              positions(2,1)], ...
                               'Zdata',[0              positions(3,1)],'visible','on');
    set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                               'Ydata',[positions(2,1) positions(2,2)], ...
                               'Zdata',[positions(3,1) positions(3,2)],'visible','on');
    set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                               'Ydata',[positions(2,2) positions(2,3)], ...
                               'Zdata',[positions(3,2) positions(3,3)],'visible','on');
    set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                               'Ydata',[positions(2,3) positions(2,4)], ...
                               'Zdata',[positions(3,3) positions(3,4)],'visible','on');
    set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                               'Ydata',[positions(2,4) positions(2,5)], ...
                               'Zdata',[positions(3,4) positions(3,5)],'visible','on');
    set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                               'Ydata',[positions(2,5) positions(2,6)], ...
                               'Zdata',[positions(3,5) positions(3,6)],'visible','on');
    set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                               'Ydata',[positions(2,6) positions(2,7)], ...
                               'Zdata',[positions(3,6) positions(3,7)],'visible','on');
    set(targetVisual,'Parent',h_axes,'Xdata',[target(1)-0.01 target(1)+0.01], ...
                               'Ydata',[target(2)-0.01 target(2)+0.01], ...
                               'Zdata',[target(3)-0.01 target(3)+0.01],'visible','on');
    drawnow;
    
pos = positions(:,end);