        if mod(i,3) == 1
            %homogeneous transformation matrix for roll (Rx)
            A(:,:,i) = [1        0                  0          0; ...
                  0   cos(theta1)       -sin(theta1)     0; ...
                  0   sin(theta1)        cos(theta1)     0; ...
                  0        0                  0          1];
            disp('roll');
        elseif mod(i,3) == 2
            %for pitch (Ry)
            A(:,:,i) = [cos(theta2)   0    sin(theta2)         0; ...
                  0             1           0            0; ...
                  -sin(theta2)  0    cos(theta2)         0; ...
                  0                0           0         1];
            disp('pitch');
        elseif mod(i,3) == 0
            %for yaw (Rz)  
            A(:,:,i) = [cos(theta3)      -sin(theta3)     0    lengths(1); ...
                  sin(theta3)       cos(theta3)     0    0; ...
                  0                      0          1    0;  ...
                  0                      0          0    1];
            disp('yaw');
        end